AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'Gemfile'

Metrics/AbcSize:
  Max: 35
Metrics/LineLength:
  Max: 119
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/EmptyLinesAroundClassBody:
  Enabled: false
