development:
  clients:
    default:
      database: rails_boilerplate_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: rails_boilerplate_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
