development:
  clients:
    default:
      database: rails_boilerplate_dev
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: rails_boilerplate_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: rails_boilerplate
      hosts:
        - <%= ENV['MONGODB_URL'] %>
      options:
        user: <%= ENV['MONGODB_USER'] %>
        password: <%= ENV['MONGODB_PASSWORD'] %>
        auth_source: <%= ENV['MONGODB_AUTH_SOURCE'] %>
        max_pool_size: 100
        min_pool_size: 5
